# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('lte-v2x-testex1.cc', ['lte-v2x'])
    obj.source = 'lte-v2x-testex1.cc'
